# Generated by Django 6.0.2 on 2026-03-05 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('frame', 'Frame'), ('background', 'Background')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.PositiveIntegerField()),
                ('is_limited', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_frame', models.ImageField(upload_to='frames/icons/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frame', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_background', models.ImageField(upload_to='backgrounds/images/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background', to='products.product')),
            ],
        ),
    ]
