# Generated by Django 6.0.2 on 2026-03-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='image_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/images/'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='icon_frame',
            field=models.ImageField(blank=True, null=True, upload_to='frames/icons/'),
        ),
    ]
