# Generated by Django 6.0.2 on 2026-03-14 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_userproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEquippedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('frame', 'Frame'), ('background', 'Background')], max_length=20, verbose_name='Тип товара')),
                ('equipped_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_by', to='products.product', verbose_name='Товар')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_items', to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'ordering': ['-equipped_at'],
                'unique_together': {('profile', 'slot')},
            },
        ),
    ]
