# Generated by Django 6.0.2 on 2026-03-19 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
        ('taskBank', '0011_merge_20260319_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattempt',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='taskBank.examsession'),
        ),
    ]
