# Generated by Django 5.2.6 on 2026-02-21 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('order_KIM', models.PositiveIntegerField(verbose_name='Номер задания из КИМ')),
                ('type', models.CharField(max_length=100, verbose_name='Тип задания из КИМ')),
                ('difficulty', models.PositiveIntegerField(verbose_name='Сложность от 1 до 5')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('answer', models.CharField(max_length=255, verbose_name='Праивльный ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['subject', 'order_KIM'],
            },
        ),
    ]
