# Generated by Django 6.0.2 on 2026-02-25 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer',
        ),
        migrations.CreateModel(
            name='TaskCorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(max_length=255, verbose_name='Правильный ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='taskBank.task')),
            ],
        ),
    ]
