# Generated by Django 6.0.2 on 2026-02-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBank', '0002_remove_task_answer_taskcorrectanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcorrectanswer',
            name='answer_text',
            field=models.TextField(max_length=25, verbose_name='Правильный ответ'),
        ),
    ]
