# Generated by Django 6.0.2 on 2026-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBank', '0003_alter_taskcorrectanswer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/images/'),
        ),
    ]
