# Generated by Django 6.0.2 on 2026-03-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskBank', '0005_taskset_tasksetitem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tasksetitem',
            name='unique_taskset_task',
        ),
        migrations.AlterUniqueTogether(
            name='tasksetitem',
            unique_together={('task_set', 'task')},
        ),
    ]
