# Generated by Django 6.0.2 on 2026-03-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskBank', '0005_task_file'),
        ('taskBank', '0006_remove_tasksetitem_unique_taskset_task_and_more'),
    ]

    operations = [
    ]
