# Generated by Django 6.0.2 on 2026-03-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBank', '0007_merge_20260308_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('prof_math', 'Профильная математика'), ('russian', 'Русский язык'), ('physics', 'Физика'), ('informatic', 'Информатика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskset',
            name='subject',
            field=models.CharField(choices=[('prof_math', 'Профильная математика'), ('russian', 'Русский язык'), ('physics', 'Физика'), ('informatic', 'Информатика')], default='prof_math', max_length=20),
            preserve_default=False,
        ),
    ]
