# Generated by Django 6.0.2 on 2026-03-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBank', '0008_alter_task_subject_alter_taskset_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('Профильная математика', 'prof_math'), ('Русский язык', 'russian'), ('Физика', 'physics'), ('Информатика', 'informatic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskset',
            name='subject',
            field=models.CharField(choices=[('Профильная математика', 'prof_math'), ('Русский язык', 'russian'), ('Физика', 'physics'), ('Информатика', 'informatic')], max_length=50),
        ),
    ]
