# Generated by Django 6.0.2 on 2026-03-19 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBank', '0009_alter_task_subject_alter_taskset_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskset',
            name='type',
            field=models.CharField(choices=[('training', 'Тренировка'), ('exam', 'Экзамен')], default='training', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('prof_math', 'Профильная математика'), ('russian', 'Русский язык'), ('physics', 'Физика'), ('informatic', 'Информатика')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskset',
            name='subject',
            field=models.CharField(choices=[('prof_math', 'Профильная математика'), ('russian', 'Русский язык'), ('physics', 'Физика'), ('informatic', 'Информатика')], max_length=50),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.PositiveIntegerField(help_text='в секундах')),
                ('is_finished', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('task_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='taskBank.taskset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
