# Generated by Django 6.0.2 on 2026-03-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskBank', '0010_alter_task_subject_alter_taskset_subject'),
        ('taskBank', '0010_taskset_type_alter_task_subject_and_more'),
    ]

    operations = [
    ]
