# Generated by Django 6.0.2 on 2026-04-07 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='Лучшая серия')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Дата последней активности')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Серия пользователя',
                'verbose_name_plural': 'Серии пользователей',
            },
        ),
    ]
