# Generated by Django 6.0.2 on 2026-03-02 14:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс очков')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелек пользователя',
                'verbose_name_plural': 'Кошельки пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Положительное значение - начисление, отрицательное - списание', verbose_name='Сумма')),
                ('reason', models.CharField(choices=[('task_complete', 'Выполнение задачи'), ('achievement', 'Получение ачивки'), ('bonus', 'Бонус'), ('purchase', 'Покупка'), ('admin_adjustment', 'Корректировка администратора')], max_length=50, verbose_name='Причина')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о транзакции', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.userwallet', verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'Транзакция кошелька',
                'verbose_name_plural': 'Транзакции кошельков',
                'ordering': ['-created_at'],
            },
        ),
    ]
