# Generated by Django 6.0.2 on 2026-03-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProduct',
        ),
    ]
