# Generated by Django 6.0.2 on 2026-03-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_taskattempt_taskprogress'),
        ('taskBank', '0010_taskset_type_alter_task_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattempt',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='taskBank.examsession'),
        ),
    ]
