# Generated by Django 6.0.2 on 2026-03-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_taskattempt_taskprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaskAttempt',
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
