# Generated by Django 6.0.2 on 2026-03-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_taskprogress_unique_together_and_more'),
        ('account', '0004_taskattempt_exam_session'),
    ]

    operations = [
    ]
