# Generated by Django 6.0.2 on 2026-03-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_20260319_2139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='userachievementprogress',
            unique_together=None,
        ),
        migrations.DeleteModel(name='Achievement'),
        migrations.DeleteModel(name='UserAchievement'),
        migrations.DeleteModel(name='UserAchievementProgress'),
    ]
