# Generated by Django 6.0.2 on 2026-03-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_type', models.CharField(choices=[('solve_tasks', 'Решить задачи'), ('first_try', 'С первого раза'), ('difficulty_master', 'Мастер сложности')], max_length=50)),
                ('target', models.PositiveIntegerField()),
                ('icon', models.ImageField(upload_to='achievements/icons/')),
                ('reward', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_achievement',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_date', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_userachievement',
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressToAchievement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_userachievementprogress',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
