# Generated by Django 6.0.2 on 2026-05-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskBank', '0012_task_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('hint', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='taskBank.task')),
            ],
            options={
                'unique_together': {('task', 'level')},
            },
        ),
    ]
